version: '3'

services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    hostname: postgres.server.local
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
 
  airflow:
    build: .
    image: airflow-local
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - grafana
    tty: true
    volumes:
       - ./dags:/root/airflow/dags
       - ./shared_dir:/shared_dir
       - ./airflow.cfg:/root/airflow/airflow.cfg
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    extra_hosts:
      - "postgres.server.local:10.5.0.5"

  shared_dir:
    image: alpine:3.16.2
    volumes:
      - ./shared_dir:/shared_dir
    tty: true
  
  grafana:
    image: grafana/grafana:9.2.2-ubuntu
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      vpcbr:

volumes:
    postgres:
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1